### ISSUE TITLE
Add script for making releases

### ISSUE THREAD

**Issue by jonte** [Pelagicore/pelux-manifests#20]
This script would create a complete release, with images, kernels, dtbs, manuals, etc. A release produced by this script can be installed by a user onto a suitable target.

**Comment by jeremiah** [comment]
I think the script ought to also have license manifest from yocto as well as installation / flashing instructions and version changelog. Perhaps these were included in your 'etc' @jonte but I wanted to be explicit :-)

**Comment by tobsan** [comment]
This would indeed be nice to have, but it should then also sync towards a release of the SWF imho.

**Comment by jeremiah** [comment]
I agree. It might then be useful as we go through the current release process for us to keep an eye on the steps. This would likely inform any script that we'd write. But maybe that is what you meant. :-)

**Comment by tobsan** [comment]
Is this still something we want? From a platform perspective it is nice, so if we create such a script we can use it as part of the release process, perhaps? Maybe this will be clearer when we do our first binary release.

**Comment by jeremiah** [comment]
I want this script. I have a homemade one for testing and it gets out of sync quickly. Having a script that more than one person uses means it'll be in decent shape and could be useful generally. I wrote mine from the SWF pretty much just cutting and pasting what was in the instructions: https://gist.github.com/jeremiah/d9e2b40eb7d4c458e35e0e533a297fb8

**Comment by tobsan** [comment]
For testing we have a CI system though. Just setting up bitbake to build isn't something we need extra scripts for imho. Perhaps we could do a TLDR version in the SWF with just those steps?

**Comment by jeremiah** [comment]
Okay, that sounds good. I'm in the middle of reading the documentation and it gets a bit hairy in the SWF when it comes time to chose a particular manifest to build. From experience I know what to do, but the code examples are vague I feel and a n00b might struggle as I am. A TLDR version would be helpful.

**Comment by thenor** [comment]
I believe this is partly solved in the current CI. We have scripts for uploading the images to the web page when we do a release. I don't know if this is what you meant @jonte. It feels like you are also including other parts of the product to be bundled together in this release-script.

@JEderonn This could be part of what we have discussed in meetings regarding our releases. That more parts may need to be bundled together with the images.

**Comment by sashko** [comment]
yes, let's close it and track future improvements on the internal Jira.

**Comment by jonte** [comment]
@thenor I'm not sure how the structure of PELUX is anymore, so I can't say if this is already done :(

The main point was to have an easy way to automatically create a release, so that no manual steps are required in creating a release. I've done this using simple scripts in the past, which as served me well.

Feel free to close if this is done or irrelevant!

**Comment by sashko** [comment]
Closing as the release process is automated now.
