### ISSUE TITLE
Refactor descriptions of specific manifests

### ISSUE THREAD

**Issue by DunderRoffe** [Pelagicore/pelux-manifests#24]
As of pull-request #23 the description of hardware specific manifests are listed in a way that does not scale very well. Hence, this documentation needs to be refactored.

One suggestion is to use a table witch maps manifests to desired image and hardware target.
Following is an example with the two hardware targets `Foo` and `Bar`:
```
 Hardware | core-image-pelux | core-image-pelux-qt
----------+------------------+--------------------
 Foo      | pelux-foo.xml    | pelux-foo-qt.xml
----------+------------------+--------------------
 Bar      | pelux-bar.xml    | pelux-bar-qt.xml
```

**Comment by socec** [comment]
Looks good to me.
