### ISSUE TITLE
repo not working with pelux-intel.xml

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux-manifests#63]
When doing this command;

`$ repo init -u https://github.com/Pelagicore/pelux-manifests.git -m pelux-intel.xml -b master`
 
I get this output; 

```
Get https://chromium.googlesource.com/external/repo
remote: Counting objects: 159, done
remote: Total 4000 (delta 2553), reused 4000 (delta 2553)
Receiving objects: 100% (4000/4000), 1.53 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (2553/2553), done.
From https://chromium.googlesource.com/external/repo
 * [new branch]      master          -> origin/master
 * [new branch]      stable          -> origin/stable
 * [new branch]      stable-next     -> origin/stable-next
 * [new branch]      stable-previous -> origin/stable-previous
 * [new branch]      upstream/maint  -> origin/upstream/maint
 * [new branch]      upstream/master -> origin/upstream/master
 * [new branch]      upstream/stable -> origin/upstream/stable
 * [new tag]         v1.0            -> v1.0
 
. . .  (lots of versions go by)

object 69034721e607ecbe8dad736c8ce07d91efdc8353
type commit
tag v1.12.37-cr1
tagger Mike Frysinger <vapier@chromium.org> 1476811349 -0400

Chromium-specific release

gpg: Signature made Tue 18 Oct 2016 01:22:29 PM EDT
gpg:                using RSA key DA03FD3916B500A8
gpg: Can't check signature: No public key
```

Then I do a 

```
$ repo sync
error: command 'sync' requires repo to be installed first.
         Use "repo init" to install it here.
```
But I've already done a repo init and receiving the manifest fails.

**Comment by jeremiah** [comment]
After moving the repo file from another location to the pelux directory, repo can successfully sync. Unsure why repeated calls to 'repo init' failed to install it in the given directory.

**Comment by tobsan** [comment]
That sounds weird, you shouldn't have to move around the repo script at all as long as it is in your PATH. There could sometimes be issues if you already have a .repo file however, but can't say anything more specific really.

However, the URL to the repo tool itself we use in PELUX is this: https://storage.googleapis.com/git-repo-downloads/repo, dunno if that could be an issue.

**Comment by DunderRoffe** [comment]
@jeremiah  It would be helpful to see the stuff in ". . .  (lots of versions go by)" I suspect there is a juicy error message lurking there :)

**Comment by jeremiah** [comment]
It was a lot of this;
` * [new tag]         v1.0            -> v1.0`
Which I thought was irrelevant. In any case, installing repo into $( pwd ) helped.

**Comment by jeremiah** [comment]
@tobsan Hmm, I don't think it was actually in my path, perhaps that was the problem. I had it on my system for doing Android development since it comes with the SDK, but I'm not sure if it was in my $PATH. I called it using the full location path but that didn't help, it needs to read some local data in .repo apparently. Fixed now. :-)

**Comment by jeremiah** [comment]
FWIW, here is a quick and oh-so-dirty script based on the steps I took. The script works on Debian Jessie 9.1 but not on Debian Buster (testing).

```
#!/bin/bash

# Ensure you have repo in this dir
# from https://source.android.com/source/downloading#installing-repo

mkdir ~/bin
PATH=~/bin:$PATH

# Download the Repo tool and ensure that it is executable:
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo

repo init -u https://github.com/Pelagicore/pelux-manifests.git -m pelux-intel.xml -b master
repo sync

if [ ! -e ./build]; then
    mkdir build
fi

export TEMPLATECONF=$( pwd )/sources/meta-pelux-bsp-intel/conf/
source sources/poky/oe-init-build-env build
bitbake core-image-pelux

# Trouble shooting
# "Please use a locale setting which supports utf-8.
# Python can't change the filesystem locale after loading so we need a utf-8 when python starts or things won't work."
# export LANGUAGE=en_US.UTF-8
# export LANG=en_US.UTF-8
# export LC_ALL=en_US.UTF-8
# dpkg-reconfigure locales
```

**Comment by tobsan** [comment]
@jeremiah the .repo directory is created by repo when you call repo init, so that shouldn't be an issue. From what I can see, your script should work just fine. Did it work when you updated your locales?
