### ISSUE TITLE
Minnowboard is a64-bit Intel® Atom™ E38xx Series System on a Chip, not core i7

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux-manifests#66]
Not the same as a NUC; https://minnowboard.org/learn-more

**Comment by tobsan** [comment]
I'm not sure what the issue is here really. Just to avoid misunderstanding: from a Yocto point of view, they are the same. Building for the Minnowboard uses the `intel-corei7-64` machine setting. The same goes for the NUC, of course.

**Comment by GordanM** [comment]
@jeremiah you are right they are not the same. But, as @tobsan mentioned, from a platform development point of view (Yocto), you would use the same image and would not need separate configuration for these two hardwares.

**Comment by jeremiah** [comment]
Okay, I think I understand. We use the same BSP for a number of Intel platforms: https://www.yoctoproject.org/downloads/bsps/pyro23/intel-corei7-64

No need for a separate BSP despite the fact that we're building for a different Architecture? (Atom vs. core).

**Comment by tobsan** [comment]
Yes, that is correct.
