### ISSUE TITLE
core-image-pelux-qtauto doesn't build without neptune ui

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux-manifests#67]
bitbake core-image-pelux-qtauto
WARNING: Host distribution "Debian-9.1" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Parsing recipes: 100% |################################################################################################################################################################################################################################################| Time: 0:03:47
Parsing of 2097 .bb files complete (0 cached, 2097 parsed). 2817 targets, 342 skipped, 0 masked, 0 errors.
WARNING: No recipes available for:
  /home/jeremiah/pelux/sources/meta-pelux/recipes-qt/automotive/neptune-ui_git.bbappend
  /home/jeremiah/pelux/sources/meta-pelux/recipes-qt/automotive/qtapplicationmanager_git.bbappend
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'neptune-ui' (but /home/jeremiah/pelux/sources/meta-pelux/recipes-core/images/core-image-pelux-qtauto.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'neptune-ui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['neptune-ui']
ERROR: Required build target 'core-image-pelux-qtauto' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-pelux-qtauto', 'neptune-ui']

**Comment by tobsan** [comment]
It looks like you don't have the qt layers added to your build. Are you using the right manifest? IIRC, you need to use the qt-enabled manifest in order to get the qt layers, which in turn enables you to build this image.

@GordanM what do you think about putting this image in a conditional layer directory like we've talked about with other recipes?

**Comment by GordanM** [comment]
@tobsan I've stated the solution here: https://github.com/Pelagicore/meta-pelux/issues/31 . I would go with that.

**Comment by DunderRoffe** [comment]
@GordanM this is different since @jeremiah explicitly wants to build qtauto

**Comment by GordanM** [comment]
@DunderRoffe thanks for mentioning that! I believe it to be a user error then. Though, the previous comment is valid for @tobsan 's question.

**Comment by tobsan** [comment]
If we went with the meta-pelux/#31, then the qt image wouldn't be visible without the layer being there hence eliminating the problem.

**Comment by jeremiah** [comment]
I forgot to pull in the correct manifest. Still, when source a new build I get the option to build core-pelux-intel or core-pelux-intel-qtauto. This is a little confusing when it is not in fact available.

**Comment by jeremiah** [comment]
Fix: to build the core-pelux-intel-qtauto bring in the pelux-intel-qtauto manifest to allow bitbaking.
